### ISSUE TITLE
Create config.py file that will contain authentication information.

### ISSUE THREAD

**Issue by Broham** [Broham/ProvidenceCrawler#4]
This file should be added to the `.gitignore` file as it will eventually contain sensitive information.

**Comment by Eddog53** [comment]
Created a blank config.py file....blank

**Comment by Broham** [comment]
Sweet @Eddog53 - did you create the new file on it's own branch or is it in master?

Take a look at this issue next:

https://github.com/Broham/ProvidenceCrawler/issues/7
